name: absen

on:
  schedule:
    - cron: '0 0-10 * * 1-5'

jobs:
  absen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v2
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Jakarta
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install
      - name: Build the files
        run: npm run build
      - name: Run the script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npm run start